###############################################################################################
package App::Billing::Universal;
###############################################################################################


use constant NSFDEST_ARRAY => 0;
use constant NSFDEST_FILE => 1;
use constant NSF_HALLEY => '0';
use constant NSF_ENVOY => '1';
use constant NSF_THIN => '2';
use constant MEDICARE => '4';
use constant MEDICAID => '5';
use constant WORKERSCOMP => '6';
use constant THIN_COMMERCIAL => 'F';
use constant THIN_MEDICARE => 'C';
use constant THIN_MEDICAID => 'D';
use constant THIN_BLUESHIELD => 'G';


use constant CLAIM_TYPE_WORKCOMP => 6;

use constant FORM_RED => 0.7;
use constant FORM_GREEN => 0.0;
use constant FORM_BLUE => 0.0;
use constant FORM_BAR_RED => 1;
use constant FORM_BAR_GREEN => 0.7;
use constant FORM_BAR_BLUE => 0.7;
use constant FORM_FONT_SIZE => 6.0;
use constant FORM_FONT_NAME => 'Helvetica';
use constant FORM_OTHER_FONT_NAME => 'Times-Italic';

use constant CHECK_BOX_W => 11;
use constant CHECK_BOX_H => 11;

use constant CHECKED_BOX_X => 3;
use constant CHECKED_BOX_Y => 3;

use constant PAGE_HEIGHT => 792;
use constant PAGE_WIDTH => 612;
use constant DATE_LINE_HEIGHT => 14;
use constant THIN_LINE_WIDTH => 0.5;
use constant THICK_LINE_WIDTH => 2;
use constant NORMAL_LINE_WIDTH  => 1;

use constant START_X => 24;
use constant START_Y => 39;
use constant FORM_WIDTH => 567;
use constant FORM_HEIGHT => 661.5;
use constant LINE_SPACING => 22.5;
use constant MEDICARE_EXTRA_SPACE => 4.5;
use constant STARTX_BOX3_SPACE => 205;    # DISTANCE B/W STARTING X AND BOX3
use constant STARTX_BOX1A_SPACE => 351.5; # DISTANCE B/W STARTING X AND BOX1A 
use constant STARTX_BOX24E_SPACE => 292; # DISTANCE B/W STARTING X AND BOX24E 
use constant STARTX_BOX24ADATE_SPACE => 67; # DISTANCE B/W STARTING X AND BOX24AD
use constant STARTX_BOX24B_SPACE => 127; # DISTANCE B/W STARTING X AND BOX24B
use constant STARTX_BOX24C_SPACE => 149; # DISTANCE B/W STARTING X AND BOX24C
use constant STARTX_BOX24D_SPACE => 172; # DISTANCE B/W STARTING X AND BOX24D
use constant STARTX_BOX24F_SPACE => 351; # DISTANCE B/W STARTING X AND BOX24F
use constant STARTX_BOX24FC_SPACE => 391; # DISTANCE B/W STARTING X AND BOX24FC
use constant STARTX_BOX24G_SPACE => 416; # DISTANCE B/W STARTING X AND BOX24G
use constant STARTX_BOX24H_SPACE => 436; # DISTANCE B/W STARTING X AND BOX24H
use constant STARTX_BOX24I_SPACE => 459; # DISTANCE B/W STARTING X AND BOX24I
use constant STARTX_BOX24J_SPACE => 478; # DISTANCE B/W STARTING X AND BOX24I
use constant STARTX_BOX24K_SPACE => 500; # DISTANCE B/W STARTING X AND BOX24J
use constant STARTX_BOX26_SPACE => 156; # DISTANCE B/W STARTING X AND BOX2A 
use constant STARTX_BOX29_SPACE => 430; # DISTANCE B/W STARTING X AND BOX1A 
use constant STARTX_BOX27_SPACE => 261; # DISTANCE B/W STARTING X AND BOX1A 
use constant BLACK_DASH => 4.5; # 
use constant WHITE_DASH => 1.125; # 
use constant CELL_PADDING_Y => 1.125; # 
use constant CELL_PADDING_X => 2.25; # 
use constant DATA_PADDING_X => 9;
use constant BOX24_HEIGHT => 8;

use constant STARTY_MID_SPACE => 374; # DISTANCE B/W STARTING Y AND MID THICK LINE 

use constant DATA_RED => 0.0;
use constant DATA_GREEN => 0.0;
use constant DATA_BLUE => 0.0;
use constant DATA_FONT_SIZE => 8.0;
use constant DATA_FONT_NAME => 'Courier';



use Exporter;

use vars qw(@ISA @EXPORT);

@ISA = qw(Exporter);
@EXPORT = qw(NSFDEST_ARRAY NSFDEST_FILE NSF_HALLEY NSF_ENVOY NSF_THIN
				FORM_RED FORM_GREEN FORM_BLUE FORM_BAR_RED FORM_BAR_GREEN 
				FORM_BAR_BLUE FORM_FONT_SIZE FORM_FONT_NAME FORM_OTHER_FONT_NAME 
				CHECK_BOX_W CHECK_BOX_H CHECKED_BOX_X CHECKED_BOX_Y PAGE_HEIGHT 
				PAGE_WIDTH DATE_LINE_HEIGHT THIN_LINE_WIDTH THICK_LINE_WIDTH 
				NORMAL_LINE_WIDTH START_X START_Y FORM_WIDTH FORM_HEIGHT 
				LINE_SPACING MEDICARE_EXTRA_SPACE STARTX_BOX3_SPACE STARTX_BOX1A_SPACE 
				STARTX_BOX24E_SPACE STARTX_BOX24ADATE_SPACE STARTX_BOX24B_SPACE 
				STARTX_BOX24C_SPACE STARTX_BOX24D_SPACE STARTX_BOX24F_SPACE 
				STARTX_BOX24FC_SPACE STARTX_BOX24G_SPACE STARTX_BOX24H_SPACE 
				STARTX_BOX24I_SPACE STARTX_BOX24J_SPACE STARTX_BOX24K_SPACE 
				STARTX_BOX26_SPACE STARTX_BOX29_SPACE STARTX_BOX27_SPACE 
				BLACK_DASH WHITE_DASH CELL_PADDING_Y CELL_PADDING_X DATA_PADDING_X 
				BOX24_HEIGHT STARTY_MID_SPACE DATA_RED DATA_GREEN DATA_BLUE DATA_FONT_SIZE 
				DATA_FONT_NAME CLAIM_TYPE_WORKCOMP MEDICARE MEDICAID WORKERSCOMP
				THIN_COMMERCIAL THIN_MEDICARE THIN_MEDICAID THIN_BLUESHIELD);


1;



